linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosec
    - bodyclose
    - ineffassign
    - unused
    - gofumpt
    - goimports
    - unconvert
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
