name: server-ci

on:
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/server-pr.yml"
      - ".github/workflows/server-checks.yml"

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/server-checks.yml
